### ISSUE TITLE
socket.error: [Errno 98] Address already in use

### ISSUE THREAD

**Issue by ddos-scripts2020** [LevyHsu/CF-Cannon#2]
print "Json:",demjson.encode({
        'T':8, #Threads
        'url': 'https://panel.brighthost.cl',
        'path': '/index.php',
        'charset': 'utf-8',
        'is_protected_by_cf': True,
        'threadCount': 2000,
        'peerCount': 10,
        'keywords':'php'
    })
    app.run(host='0.0.0.0',port=80)

**Comment by LevyHsu** [comment]
That means your port 80 is already occupied by other services, typically a web server.
