### ISSUE TITLE
Could not run

### ISSUE THREAD

**Issue by N0ise1337** [LevyHsu/CF-Cannon#3]
Couldnt run the script using python3 BypassCF.py www. .... 
File "BypassCF.py", line 142
    UA = 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.%s.92 Safari/537.36' % str(random.randint(0001,9999))
                                                                                                                                               ^
SyntaxError: invalid token

**Comment by N0ise1337** [comment]
Is there any solution please?

**Comment by LevyHsu** [comment]
run attack.py not BypassCF.py
please at least read Readme

**Comment by N0ise1337** [comment]
Aight ran it and showed me the Flask app, but i wanna bypass uam what should i do?

**Comment by N0ise1337** [comment]
Alright i handled to run attack.py but did not understand how that work, modified the url in attack.py and, 
Didnt understand what i'm supposed to do in api tester

**Comment by N0ise1337** [comment]
Also how BypassCF works?

**Comment by N0ise1337** [comment]
I don't know as you showed up a tutorial for cf_cannon.py but i dont see any file named cf_cannon.py

**Comment by LevyHsu** [comment]
1. by running attack.py you start a public server, POST a JSON request with attack Infos to this server with corresponding path and port.
2. Magic

**Comment by N0ise1337** [comment]
How do i post this json using api tester? Got the json but dont know how to post it
